Make instructions clearer for patching single library
awsdocs/aws-xray-developer-guide pull request #13
Opened 2019-12-11 01:06 UTC by StephenGoodall

https://github.com/aws/aws-xray-sdk-python/issues/71

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2019-12-11 17:38 UTC, willarmiros requested changes
Hi @StephenGoodall,
Thank you for the contribution. I've left some suggestions in the comments.

2019-12-11 17:38 UTC, willarmiros commented on doc-source/xray-sdk-python-patching.md
> +
Please remove this example from the PR. We typically only have 1 recommended way of doing something in the documentation, and the other example is more consistent with other patching calls.

2019-12-11 17:38 UTC, willarmiros commented on doc-source/xray-sdk-python-patching.md
> +**Example main\.py – patch single library (trailing comma)**
"Trailing comma" specification no longer needed.

2019-12-11 23:42 UTC, StephenGoodall commented
Hi @willarmiros I've made those changes 😃 
Let me know if it needs anything else!

2019-12-12 00:02 UTC, willarmiros approved these changes

2019-12-18 22:46 UTC, merged

2019-12-18 22:52 UTC, alivest commented
Thank you Stephen!